global using static Source.Dbg;
global using static Source.Common.CFormatting;
global using static Source.PlatformMacros;
global using static Source.Common.MemUtils;
global using static Source.Common.ThreadUtils;
global using static Source.Common.Engine.ImportUtils;
global using static Source.Common.Mathematics.MathLibConsts;
global using static Source.GlobalReflectionUtils;
global using static Source.Common.RecvPropHelpers;
global using static Source.Common.SendPropHelpers;
global using CRC32_t = uint;
global using HCursor = nint;
global using UtlSymId_t = ulong;
global using vec_t = float;
global using FileNameHandle_t = ulong;
global using FileFindHandle_t = ulong;
global using PackedEntityHandle_t = nint;
